### ISSUE TITLE
Typo in homepage

### ISSUE THREAD

**Issue by Sam44323** [AbhinavRobinson/open-auto-demo-ui#1]
It should be **Vehicle** @AbhinavRobinson
<img width="574" alt="Screenshot 2022-05-29 at 2 33 13 PM" src="https://user-images.githubusercontent.com/65643151/170860465-27d71f67-bd50-4e1e-9746-4a39ff044d21.png">

**Comment by AbhinavRobinson** [comment]
Fixed on next commit! 👋 @Sam44323
